language: python
python:
  - 3.6
services:
  - docker
sudo: required
install:
  - pip install -r requirements-doc.txt
  - pip install mypy
script:
  - python3 -m py_compile check_mk_web_api/*.py
  - mypy check_mk_web_api/__init__.py check_mk_web_api/exception.py
  - docker run -d --rm -p 127.0.0.1:8080:5000 --name check-mk checkmk/check-mk-raw:1.5.0-latest
  - sleep 60
  - docker exec -u cmk check-mk bash -c "echo automation-secret > /omd/sites/cmk/var/check_mk/web/automation/automation.secret"
  - CHECK_MK_URL=http://localhost:8080/cmk/check_mk CHECK_MK_USER=automation CHECK_MK_SECRET=automation-secret python setup.py test
  - docker stop check-mk
  - docker run -d --rm -p 127.0.0.1:8080:5000 --name check-mk checkmk/check-mk-raw:1.6.0-latest
  - sleep 60
  - docker exec -u cmk check-mk bash -c "echo automation-secret > /omd/sites/cmk/var/check_mk/web/automation/automation.secret"
  - CHECK_MK_URL=http://localhost:8080/cmk/check_mk CHECK_MK_USER=automation CHECK_MK_SECRET=automation-secret python setup.py test
  - docker stop check-mk
  - cd doc
  - pydocmd build
  - cd ..
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: doc/_build/site
 on:
   branch: master
